[package]
name = "yokai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = "1.0.6"
macroquad = "0.3"
fastrand = "1.7.0"
num-format = "0.4.0" # converts integers to comma-separated strings